// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzdkhqltpvojyyvvszbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6ZGtocWx0cHZvanl5dnZzemJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODMwODYsImV4cCI6MjA1NTI1OTA4Nn0.GgdS96ZlH7oPSo5t0-1lVSiNMegIiLEh2DDEM29R5Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);